version: '3.5'
services:
  php:
    container_name: php-pruebas-esi
    image: lucaspintos909/php-pdo-mysqli
    ports:
      - 80:80
    volumes:
      - ./:/var/www/html
    depends_on:
      - db

  db:
    container_name: db-pruebas-esi
    image: mysql:8.0 # Imagen de docker-hub de mysql en la version 8.0
    environment:
      MYSQL_DATABASE: pruebas_esi
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 3306:3306
    volumes:
      - ./mysql:/var/lib/mysql