version: '3.5'
services:
    php:
      container_name: php
      image: lucaspintos909/php-pdo-mysqli:latest
      ports:
        - 8080:80
      volumes:
        - ./src:/var/www/html/
      depends_on:
        - db
      networks:
        - docker-net

    db:
      container_name: db
      image: mysql:8.0
      environment:
        MYSQL_DATABASE: pruebas_db
        MYSQL_USER: admin
        MYSQL_PASSWORD: admin
        MYSQL_ROOT_PASSWORD: root
      ports:
        - 3360:3306
      volumes:
        - ./mysql:/var/lib/mysql
      networks:
        - docker-net

networks:
  docker-net:
    driver: bridge
