version: '3.5'
services:
    php:
      container_name: php_esi
      build: .
      ports:
        - 8080:80
      volumes:
        - ./src:/var/www/html/
      depends_on:
        - db
      networks:
        - docker-net

    db:
      container_name: db_esi
      image: mariadb:10
      environment:
        MYSQL_DATABASE: tareas_esi
        MYSQL_USER: admin
        MYSQL_PASSWORD: admin
        MYSQL_ROOT_PASSWORD: root
      ports:
        - 3306:3306
      volumes:
        - ./mysql:/var/lib/mysql
        - ./tablas.sql:/docker-entrypoint-initdb.d/setup.sql # Archivo para la creacion de las tablas
      networks:
        - docker-net

networks:
  docker-net:
    driver: bridge
