# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
# Use a package of configuration called an orb.
jobs:
  build:
    machine: true
    steps:
      - add_ssh_keys:
          fingerprints:
            - "f4:0e:ef:76:d9:5d:0b:8b:60:d5:f3:95:f4:ec:df:11"
      - checkout
      - run:
          name: DockerHub Login
          command: docker login -u $DOCKER_USER -p $DOCKER_PASS
      - run:
          name: Docker Build
          command: docker build -t lucaspintos909/esi-pruebas:$CIRCLE_SHA1 .
      - run:
          name: Docker Push to lucaspintos909/esi-pruebas
          command: docker push lucaspintos909/esi-pruebas:$CIRCLE_SHA1
      - run:
          name: Script deploy.sh
          command: ssh -o StrictHostKeyChecking=no ubuntu@tests.lucaspintos.tech "/bin/bash /home/ubuntu/esi-pruebas/deploy/deploy.sh $CIRCLE_SHA1"