version: 2.1

workflows: # Define a Workflow running the build job, then the deploy job
  version: 2
  build-deploy: # Make a workflow to build and deploy your project
    jobs:
      - build:
          filters:
            branches:
              only: main # Only deploy when the commit is on the Master branch
jobs:
  build:
    machine: true
    steps:
      - add_ssh_keys:
          # Fingerprint que me da circleci
          fingerprints:
            - "f4:0e:ef:76:d9:5d:0b:8b:60:d5:f3:95:f4:ec:df:11"
      # Chechout para que descargue el repo de github
      - checkout
      - run:
          name: DockerHub Login
          command: docker login -u $DOCKER_USER -p $DOCKER_PASS
      - run:
          name: Docker Build
          command: docker build -t lucaspintos909/esi-pruebas:$CIRCLE_SHA1 .
      - run:
          name: Docker Push to lucaspintos909/esi-pruebas
          command: docker push lucaspintos909/esi-pruebas:$CIRCLE_SHA1
      - run:
          name: Script deploy.sh
          # Me conecto cons ssh al servidor y ejecuto el archivo de deploy
          command: ssh -o StrictHostKeyChecking=no ubuntu@esi.lucaspintos.tech "/bin/bash /home/ubuntu/esi-pruebas/deploy/deploy.sh $CIRCLE_SHA1"