version: '3.5'
services:
  https-portal:
    container_name: ssl
    image: steveltn/https-portal:1
    depends_on:
      - php
    ports:
      - 80:80
      - 443:443
    restart: always
    volumes:
      - ./ssl_certs:/var/lib/https-portal
    environment:
      DOMAINS: 'tests.lucaspintos.tech -> http://34.230.185.184:8080 #production'

  php:
    container_name: php
    image: lucaspintos909/esi-pruebas:931e24bede1304b6515046e53211f6d583f6feb2
    ports:
      - 8080:80
    #volumes:
      #- ./config.php:/var/www/html/config/config.php
    depends_on:
      - db
    networks:
      - docker-net

  db:
    container_name: db
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: task_db
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 3360:3306
    volumes:
      - ./mysql:/var/lib/mysql
      - ./setup.sql:/docker-entrypoint-initdb.d/setup.sql # Archivo para inicializar la creacion de las tablas y base de datos
    networks:
      - docker-net

networks:
  docker-net:
    driver: bridge


